### ISSUE TITLE
adding VideoJack support to Xjadeo

### ISSUE THREAD

**Issue by Reaper10** [x42/xjadeo#3]
Could you adding VideoJack support to Could you adding VideoJack support to Xjadeo? http://www.piksel.org/videojack
 About VideoJack 
 video extensions for the Jack audio server

VideoJack is a mechanism to route video signals betweenapplications running on the samecomputer. It enables users of "jackified" video processingsoftware to publish and receive video livestreams. The current proposal is based on an extended version of the Jack audio server. In the GNU/Linux audio developer community, the Jack server is kind of an informal standard for realtime audio data exchange. An improved Jack system with videowires tries to be the same in the videoworld.

Get involved

There is amailing list for VideoJack issues.

Download

The current VideoJack source can bedownloaded from the subversion repository:
http://videojack.svn.sourceforge.net/viewvc/videojack/ 

Checkout with the following command:
 svn co https://videojack.svn.sourceforge.net/svnroot/videojack videojack 

Older tarballs and some patched clientapplications are available here. 

Hosts

The following videoapplications support VideoJack.

LiVES - (Howto use videoJack with LiVES)

UniCap

Wiki info

VideoJack

VjackDev

Credits

The original VideoJack was designed by Martin Bayer at the Piksel05 meeting in Bergen, and has been further developed by Salsaman and others in an ongoing effort to bring it to a usable state 

Gisle Frøysland from BEK organised the Piksel meeting in Bergen and is now sponsoring the virtual home of the VideoJack project.
? http://www.piksel.org/videojack
 About VideoJack 
 video extensions for the Jack audio server

VideoJack is a mechanism to route video signals betweenapplications running on the samecomputer. It enables users of "jackified" video processingsoftware to publish and receive video livestreams. The current proposal is based on an extended version of the Jack audio server. In the GNU/Linux audio developer community, the Jack server is kind of an informal standard for realtime audio data exchange. An improved Jack system with videowires tries to be the same in the videoworld.

Get involved

There is amailing list for VideoJack issues.

Download

The current VideoJack source can bedownloaded from the subversion repository:
http://videojack.svn.sourceforge.net/viewvc/videojack/ 

Checkout with the following command:
 svn co https://videojack.svn.sourceforge.net/svnroot/videojack videojack 

Older tarballs and some patched clientapplications are available here. 

Hosts

The following videoapplications support VideoJack.

LiVES - (Howto use videoJack with LiVES)

UniCap

Wiki info

VideoJack

VjackDev

Credits

The original VideoJack was designed by Martin Bayer at the Piksel05 meeting in Bergen, and has been further developed by Salsaman and others in an ongoing effort to bring it to a usable state 

Gisle Frøysland from BEK organised the Piksel meeting in Bergen and is now sponsoring the virtual home of the VideoJack project.

**Comment by x42** [comment]
Last time I used video-jack (6 or 7 years ago), it was not possible to jack (audio) and video-jack in the same program. A quick look at https://svn.code.sf.net/p/videojack/code/ indicates that it has not changed since.

Since jack (audio) is an integral part of xjadeo this cannot be done by design.

Video-jack provides a live-stream (like jack audio) of video-data. it is not possible to seek in that stream.
decoder and display are separate.

Theoretically xjadeo could be broken into pieces. A decoder app which just sends its output to a video-jack port (instead of displaying it directly), and a standalone display-only app, but it is not feasible to do that.

xjadeo is designed with a hardware display in mind and the individual parts are coupled (on screen display of timecode, interaction with the display to control the decoder, not to mention various remote control surfaces).

libharvid from https://github.com/x42/harvid would lend itself better to decode into a shared-memory area as per video-jack spec. It's also independent of jack.  

Either way, an application that feeds videojack would be an entirely separate project.

While video-jack is a "cool quick hack" I still don't see it take off anytime soon. Actually less so that 10 years ago when video-jack started. This is because video-data increased a lot (PAL -> 4K). and because the concepts that apply to jack-audio (fixed sample-rate, float is sufficient) do not apply to video (different geometries, different colorspace, etc etc).
